#!/usr/bin/env python3
"""Rebuild the endpoint indexes used by the skills.

Reads llms.txt, walks the sections owned by a skill and writes one compact
index per skill: endpoint, what it returns, and the URL of its documentation
page. The documentation itself stays upstream, the skills only need to know
where to look.
"""

import re
import sys
import urllib.request
from collections import defaultdict
from pathlib import Path

DOCS_PREFIX = "https://twelvedata.com/docs/llms/"
LLMS_TXT_URL = "https://twelvedata.com/docs/llms.txt"
SKILLS_DIR = Path(__file__).resolve().parent.parent / "skills"
USER_AGENT = "twelvedata-skills-sync/0.1"

# Sections of llms.txt that end up in an endpoint index, and their owner skill.
SECTION_OWNERS = {
    "market-data.md": "twelvedata-api",
    "reference-data.md": "twelvedata-api",
    "currencies.md": "twelvedata-api",
    "fundamentals.md": "twelvedata-api",
    "analysis.md": "twelvedata-api",
    "regulatory.md": "twelvedata-api",
    "advanced.md": "twelvedata-api",
    "technical-indicators.md": "twelvedata-indicators",
    "etfs.md": "twelvedata-funds",
    "mutual-funds.md": "twelvedata-funds",
    "money-market-funds.md": "twelvedata-funds",
}

# Sections that deliberately have no index: the skills link their pages directly.
IGNORED_SECTIONS = frozenset(
    {
        "introduction.md",
        "websocket/ws-overview.md",
        "websocket/ws-real-time-price.md",
        "ai/integrations.md",
        "ai/integrations/chatgpt.md",
        "ai/integrations/near-agent.md",
        "ai/integrations/openclaw.md",
        "ai/mcp-server.md",
        "ai/world-model-dataset.md",
    }
)

ENTRY_PATTERN = re.compile(
    r"\[([^\]]+)\]\(" + re.escape(DOCS_PREFIX) + r"([^)\s]+\.md)\):\s*(.+)"
)
HEADING_PATTERN = re.compile(r"^#\s+(.+)$", re.MULTILINE)

HEADER = (
    "# Endpoint index\n\n"
    "Generated by `scripts/sync_references.py` from {source}.\n"
    "Each line is an endpoint and the page documenting its parameters and response.\n"
    "Credit prices are not on these lines. Read `twelvedata-api` before assuming a call costs 1.\n"
).format(source=LLMS_TXT_URL)


def fetch(url: str) -> str:
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=30) as response:
        return response.read().decode("utf-8")


def render_section(index: str) -> tuple[str, list[str]]:
    heading = HEADING_PATTERN.search(index)
    title = heading.group(1).strip() if heading else "Endpoints"
    lines = [
        f"- `{endpoint}` {summary.strip()} - {DOCS_PREFIX}{page}"
        for endpoint, page, summary in ENTRY_PATTERN.findall(index)
    ]
    return title, lines


def main(argv: list[str]) -> int:
    check = "--check" in argv

    catalog = fetch(LLMS_TXT_URL)
    sections = dict.fromkeys(
        re.findall(re.escape(DOCS_PREFIX) + r"([^)\s]+\.md)", catalog)
    )

    unknown = sorted(set(sections) - set(SECTION_OWNERS) - IGNORED_SECTIONS)
    if unknown:
        print("New sections in llms.txt, own or ignore them:", ", ".join(unknown))
        return 1

    # Nothing is written until every section parses, so a failure below leaves
    # the existing indexes intact.
    per_skill = defaultdict(list)
    for section in sections:
        skill = SECTION_OWNERS.get(section)
        if skill is None:
            continue
        title, lines = render_section(fetch(DOCS_PREFIX + section))
        if not lines:
            print(f"no endpoints parsed from {section}, upstream format changed")
            return 1
        per_skill[skill].append(f"## {title}\n\n" + "\n".join(lines) + "\n")

    stale = False
    for skill, blocks in per_skill.items():
        path = SKILLS_DIR / skill / "references" / "endpoints.md"
        content = HEADER + "\n" + "\n".join(blocks)
        if path.exists() and path.read_text(encoding="utf-8") == content:
            print(f"unchanged {skill}")
            continue
        if check:
            print(f"stale {path.relative_to(SKILLS_DIR.parent)}")
            stale = True
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"updated {path.relative_to(SKILLS_DIR.parent)}")

    return 1 if stale else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
